services:
  parewa:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: parewa
    env_file:
      - .env # Load environment variables from the .env file
    ports:
      - "5001:5000" # Map host port 5001 to container port 5000 (where Flask runs)
    restart: unless-stopped